# Movie Recommendation System - Data Preprocessing

This notebook prepares the TMDB 5000 datasets for downstream vectorization and recommendation modeling.

### 1). Import Required libraries

In [2]:
import pandas as pd
import numpy as np
import ast

## Load Source Datasets
Load the movies and credits files, then inspect shape and sample rows.

### 2) Load datasets

In [3]:
movies = pd.read_csv("../data/tmdb_5000_movies.csv")
credits = pd.read_csv("../data/tmdb_5000_credits.csv")

In [4]:
movies.shape

(4803, 20)

In [178]:
 credits.shape

(4803, 4)

In [179]:
movies.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""name"": ""Fantasy""}, {""id"": 878, ""name"": ""...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"": 2964, ""name"": ""future""}, {""id"": 3386, ""name"": ""space war""}, {""id"": 33...",en,Avatar,"In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn bet...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289}, {""name"": ""Twentieth Century Fox Film Corporation"", ""id"": 306}, {""na...","[{""iso_3166_1"": ""US"", ""name"": ""United States of America""}, {""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""}]",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""name"": ""Fantasy""}, {""id"": 28, ""name"": ""Action""}]",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""name"": ""drug abuse""}, {""id"": 911, ""name"": ""exotic island""}, {""id"": 1319,...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, has come back to life and is headed to the edge of the Earth with Will T...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""name"": ""Jerry Bruckheimer Films"", ""id"": 130}, {""name"": ""Second Mate Pr...","[{""iso_3166_1"": ""US"", ""name"": ""United States of America""}]",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500

In [180]:
credits.head(2)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""credit_id"": ""5602a8a7c3a3685532001c9a"", ""gender"": 2, ""id"": 65731, ""nam...","[{""credit_id"": ""52fe48009251416c750aca23"", ""department"": ""Editing"", ""gender"": 0, ""id"": 1721, ""job"": ""Editor"", ""name""..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Sparrow"", ""credit_id"": ""52fe4232c3a36847f800b50d"", ""gender"": 2, ""id"": 85,...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""department"": ""Camera"", ""gender"": 2, ""id"": 120, ""job"": ""Director of Photo..."

In [181]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

In [182]:
credits.columns

Index(['movie_id', 'title', 'cast', 'crew'], dtype='object')

## Rename Identifier Column
Rename `id` in the movies dataset to `movie_id` so both datasets share a consistent merge key.

### 3) Rename the movie id column for consistency

In [183]:
movies = movies.rename(columns={"id":"movie_id"})

In [184]:
movies.columns.tolist()[:12]

['budget',
 'genres',
 'homepage',
 'movie_id',
 'keywords',
 'original_language',
 'original_title',
 'overview',
 'popularity',
 'production_companies',
 'production_countries',
 'release_date']

### 4) Keep only relevant columns from credits and normalize movie_id types

In [185]:
credits.columns

Index(['movie_id', 'title', 'cast', 'crew'], dtype='object')

In [186]:
credits = credits[["movie_id", "cast", "crew"]].copy()

In [187]:
credits.head()

,movie_id,cast,crew
0,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""credit_id"": ""5602a8a7c3a3685532001c9a"", ""gender"": 2, ""id"": 65731, ""nam...","[{""credit_id"": ""52fe48009251416c750aca23"", ""department"": ""Editing"", ""gender"": 0, ""id"": 1721, ""job"": ""Editor"", ""name""..."
1,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Sparrow"", ""credit_id"": ""52fe4232c3a36847f800b50d"", ""gender"": 2, ""id"": 85,...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""department"": ""Camera"", ""gender"": 2, ""id"": 120, ""job"": ""Director of Photo..."
2,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""credit_id"": ""52fe4d22c3a368484e1d8d6b"", ""gender"": 2, ""id"": 8784, ""name"":...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""department"": ""Sound"", ""gender"": 2, ""id"": 153, ""job"": ""Original Music Com..."
3,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Batman"", ""credit_id"": ""52fe4781c3a36847f8139869"", ""gender"": 2, ""id"": 389...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""department"": ""Sound"", ""gender"": 2, ""id"": 947, ""job"": ""Original Music Com..."
4,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""credit_id"": ""52fe479ac3a36847f813ea75"", ""gender"": 2, ""id"": 60900, ""name...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""department"": ""Writing"", ""gender"": 2, ""id"": 7, ""job"": ""Screenplay"", ""name..."

#### Now numeric to  all the values

In [188]:
movies["movie_id"] = pd.to_numeric(movies["movie_id"], errors="coerce")
credits["movie_id"] = pd.to_numeric(credits["movie_id"], errors="coerce")

In [189]:
movies["movie_id"].head()

0     19995
1       285
2    206647
3     49026
4     49529
Name: movie_id, dtype: int64

In [190]:
movies.isnull().sum()

budget                     0
genres                     0
homepage                3091
movie_id                   0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
dtype: int64

In [192]:
credits.head()

,movie_id,cast,crew
0,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""credit_id"": ""5602a8a7c3a3685532001c9a"", ""gender"": 2, ""id"": 65731, ""nam...","[{""credit_id"": ""52fe48009251416c750aca23"", ""department"": ""Editing"", ""gender"": 0, ""id"": 1721, ""job"": ""Editor"", ""name""..."
1,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Sparrow"", ""credit_id"": ""52fe4232c3a36847f800b50d"", ""gender"": 2, ""id"": 85,...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""department"": ""Camera"", ""gender"": 2, ""id"": 120, ""job"": ""Director of Photo..."
2,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""credit_id"": ""52fe4d22c3a368484e1d8d6b"", ""gender"": 2, ""id"": 8784, ""name"":...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""department"": ""Sound"", ""gender"": 2, ""id"": 153, ""job"": ""Original Music Com..."
3,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Batman"", ""credit_id"": ""52fe4781c3a36847f8139869"", ""gender"": 2, ""id"": 389...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""department"": ""Sound"", ""gender"": 2, ""id"": 947, ""job"": ""Original Music Com..."
4,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""credit_id"": ""52fe479ac3a36847f813ea75"", ""gender"": 2, ""id"": 60900, ""name...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""department"": ""Writing"", ""gender"": 2, ""id"": 7, ""job"": ""Screenplay"", ""name..."

In [193]:
credits.isnull().sum()

movie_id    0
cast        0
crew        0
dtype: int64

#### Delete the those have no movies (NAN)

In [194]:
print(movies["movie_id"].dtype)
print(credits["movie_id"].dtype)

int64
int64

In [195]:
movies.shape

(4803, 20)

In [196]:
credits.shape

(4803, 3)

In [197]:
movies = movies.dropna(subset=["movie_id"]).copy()

In [198]:
movies.isnull().sum()

budget                     0
genres                     0
homepage                3091
movie_id                   0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
dtype: int64

In [199]:
credits = credits.dropna(subset=["movie_id"]).copy()

In [200]:
credits.isnull().sum()

movie_id    0
cast        0
crew        0
dtype: int64

In [208]:
movies.duplicated().sum()
credits.duplicated().sum()

np.int64(0)

### Now all objective values convert into integer form

In [209]:
movies["movie_id"] = movies["movie_id"].astype(int)
credits["movie_id"] = credits["movie_id"].astype(int)

In [210]:
print("Movies rows after id normalization:", movies.shape[0])
print("Credits rows after id normalization:", credits.shape[0])

Movies rows after id normalization: 4803
Credits rows after id normalization: 4803

### 5) Merge movies and credits on movie_id

In [ ]:
credits = credits.drop_duplicates(subset=["movie_id"]).copy()

In [211]:
merged_movies = movies.merge(
    credits,
    on="movie_id",
    how="inner",
    validate="one_to_one"
)

### Safety deduplication step (should not remove anything with one_to_one validation).

In [212]:
before_dedup = merged_movies.shape[0]

In [213]:
before_dedup

4803

In [214]:
merged_movies = merged_movies.drop_duplicates(subset=["movie_id"]).reset_index(drop=True)

In [216]:
merged_movies.head(2)

,budget,genres,homepage,movie_id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""name"": ""Fantasy""}, {""id"": 878, ""name"": ""...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"": 2964, ""name"": ""future""}, {""id"": 3386, ""name"": ""space war""}, {""id"": 33...",en,Avatar,"In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn bet...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289}, {""name"": ""Twentieth Century Fox Film Corporation"", ""id"": 306}, {""na...","[{""iso_3166_1"": ""US"", ""name"": ""United States of America""}, {""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""}]",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,Enter the World of Pandora.,Avatar,7.2,11800,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""credit_id"": ""5602a8a7c3a3685532001c9a"", ""gender"": 2, ""id"": 65731, ""nam...","[{""credit_id"": ""52fe48009251416c750aca23"", ""department"": ""Editing"", ""gender"": 0, ""id"": 1721, ""job"": ""Editor"", ""name""..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""name"": ""Fantasy""}, {""id"": 28, ""name"": ""Action""}]",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""name"": ""drug abuse""}, {""id"": 911, ""name"": ""exotic island""}, {""id"": 1319,...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, has come back to life and is headed to the edge of the Earth with Will T...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""name"": ""Jerry Bruckheimer Films"", ""id"": 130}, {""name"": ""Second Mate Pr...","[{""iso_3166_1"": ""US"", ""name"": ""United States of America""}]",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,"[{""cast_id"": 4, ""character"": ""Captain Jack Sparrow"", ""credit_id"": ""52fe4232c3a36847f800b50d"", ""gender"": 2, ""id"": 85,...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""department"": ""Camera"", ""gender"": 2, ""id"": 120, ""job"": ""Director of Photo..."

In [217]:
after_dedup = merged_movies.shape[0]

In [218]:
after_dedup

4803

In [219]:
duplicate_count = merged_movies.duplicated(subset=["movie_id"]).sum()

In [220]:
duplicate_count

np.int64(0)

In [221]:
print("Merged shape:", merged_movies.shape)
print("Rows removed by safety deduplication:", before_dedup - after_dedup)
print("Duplicate movie_id count after merge:", duplicate_count)

Merged shape: (4803, 22)
Rows removed by safety deduplication: 0
Duplicate movie_id count after merge: 0

### Quick merged preview

In [222]:
print(merged_movies[["movie_id", "title", "cast", "crew"]].head(2))

   movie_id                                     title  \
0     19995                                    Avatar
1       285  Pirates of the Caribbean: At World's End

                                                                                                                      cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "nam...
1  [{"cast_id": 4, "character": "Captain Jack Sparrow", "credit_id": "52fe4232c3a36847f800b50d", "gender": 2, "id": 85,...

                                                                                                                      crew
0  [{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name"...
1  [{"credit_id": "52fe4232c3a36847f800b579", "department": "Camera", "gender": 2, "id": 120, "job": "Director of Photo...

## Select Required Columns
We keep only the fields needed for content-based recommendation feature engineering.

In [224]:
merged_movies.columns

Index(['budget', 'genres', 'homepage', 'movie_id', 'keywords',
       'original_language', 'original_title', 'overview', 'popularity',
       'production_companies', 'production_countries', 'release_date',
       'revenue', 'runtime', 'spoken_languages', 'status', 'tagline', 'title',
       'vote_average', 'vote_count', 'cast', 'crew'],
      dtype='object')

### 6) Select required columns

In [225]:
required_columns = [
    "movie_id",
    "title",
    "overview",
    "genres",
    "keywords",
    "cast",
    "crew"
]

In [226]:
movies_df = merged_movies[required_columns].copy()

In [228]:
print("Selected dataframe shape:", movies_df.shape)

Selected dataframe shape: (4803, 7)

In [229]:

movies_df.head(2)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn bet...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""name"": ""Fantasy""}, {""id"": 878, ""name"": ""...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"": 2964, ""name"": ""future""}, {""id"": 3386, ""name"": ""space war""}, {""id"": 33...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""credit_id"": ""5602a8a7c3a3685532001c9a"", ""gender"": 2, ""id"": 65731, ""nam...","[{""credit_id"": ""52fe48009251416c750aca23"", ""department"": ""Editing"", ""gender"": 0, ""id"": 1721, ""job"": ""Editor"", ""name""..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, has come back to life and is headed to the edge of the Earth with Will T...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""name"": ""Fantasy""}, {""id"": 28, ""name"": ""Action""}]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""name"": ""drug abuse""}, {""id"": 911, ""name"": ""exotic island""}, {""id"": 1319,...","[{""cast_id"": 4, ""character"": ""Captain Jack Sparrow"", ""credit_id"": ""52fe4232c3a36847f800b50d"", ""gender"": 2, ""id"": 85,...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""department"": ""Camera"", ""gender"": 2, ""id"": 120, ""job"": ""Director of Photo..."

### Now 

### 7) Inspect missing values before dropping

In [230]:
missing_summary = movies_df.isnull().sum()

In [231]:
missing_summary

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

### 8) Drop rows with missing values

In [232]:
rows_before = movies_df.shape[0]

In [233]:
rows_before

4803

In [234]:
movies_df = movies_df.dropna().reset_index(drop=True)

In [237]:
rows_after = movies_df.shape[0]

In [238]:
rows_after

4800

In [239]:
print("Rows before dropna:", rows_before)
print("Rows after dropna:", rows_after)
print("Rows dropped:", rows_before - rows_after)

Rows before dropna: 4803
Rows after dropna: 4800
Rows dropped: 3

## Why `dropna()` Instead of `fillna()`?
For recommendation tags, fields like `overview`, `genres`, `cast`, and `crew` carry core semantic meaning. Filling missing values with placeholders (such as empty strings or defaults) can add noisy or misleading tokens and weaken similarity quality. Dropping incomplete rows preserves cleaner, higher-signal feature text for modeling.

### 9) Parse JSON-like columns using ast.literal_eval

In [240]:
def extract_name_list(text_value, limit=None):
    parsed = ast.literal_eval(text_value)
    names = [item["name"] for item in parsed if isinstance(item, dict) and "name" in item]
    if limit is not None:
        names = names[:limit]
    return names


def extract_director(text_value):
    parsed = ast.literal_eval(text_value)
    directors = [
        item["name"]
        for item in parsed
        if isinstance(item, dict) and item.get("job") == "Director" and "name" in item
    ]
    return directors[:1]

In [241]:
movies_df["genres"] = movies_df["genres"].apply(extract_name_list)
movies_df["keywords"] = movies_df["keywords"].apply(extract_name_list)
movies_df["cast"] = movies_df["cast"].apply(lambda x: extract_name_list(x, limit=3))
movies_df["crew"] = movies_df["crew"].apply(extract_director)

In [242]:
print("Parsed sample:")
print(movies_df[["title", "genres", "keywords", "cast", "crew"]].head(2))

Parsed sample:
                                      title  \
0                                    Avatar
1  Pirates of the Caribbean: At World's End

                                          genres  \
0  [Action, Adventure, Fantasy, Science Fiction]
1                   [Adventure, Fantasy, Action]

                                                                                                                  keywords  \
0  [culture clash, future, space war, space colony, society, space travel, futuristic, romance, space, alien, tribe, al...
1  [ocean, drug abuse, exotic island, east india trading company, love of one's life, traitor, shipwreck, strong woman,...

                                               cast              crew
0  [Sam Worthington, Zoe Saldana, Sigourney Weaver]   [James Cameron]
1     [Johnny Depp, Orlando Bloom, Keira Knightley]  [Gore Verbinski]

In [244]:
# 10) Process overview text and normalize names
movies_df["overview"] = movies_df["overview"].apply(lambda x: x.split())


def remove_inner_spaces(token_list):
    return [token.replace(" ", "") for token in token_list]

for feature_col in ["genres", "keywords", "cast", "crew"]:
    movies_df[feature_col] = movies_df[feature_col].apply(remove_inner_spaces)

print("Processed text sample:")
print(movies_df[["title", "overview", "cast", "crew"]].head(1))

Processed text sample:
    title  \
0  Avatar

                                                                                                                  overview  \
0  [In, the, 22nd, century,, a, paraplegic, Marine, is, dispatched, to, the, moon, Pandora, on, a, unique, mission,, bu...

                                            cast            crew
0  [SamWorthington, ZoeSaldana, SigourneyWeaver]  [JamesCameron]

## Create Feature-Rich `tags` Column
Combine text features (`overview`, `genres`, `keywords`, `cast`, `crew`) into one modeling column.

### 11) Create tags by combining all selected feature lists

In [245]:
movies_df["tags"] = (
    movies_df["overview"]
    + movies_df["genres"]
    + movies_df["keywords"]
    + movies_df["cast"]
    + movies_df["crew"]
)

In [246]:
print("Tags list sample:")
print(movies_df[["title", "tags"]].head(2))

Tags list sample:
                                      title  \
0                                    Avatar
1  Pirates of the Caribbean: At World's End

                                                                                                                      tags
0  [In, the, 22nd, century,, a, paraplegic, Marine, is, dispatched, to, the, moon, Pandora, on, a, unique, mission,, bu...
1  [Captain, Barbossa,, long, believed, to, be, dead,, has, come, back, to, life, and, is, headed, to, the, edge, of, t...

### 12) Final cleaning: convert tags list to lowercase text

In [247]:
movies_df["tags"] = movies_df["tags"].apply(lambda values: " ".join(values).lower())

final_movies_df = movies_df[["movie_id", "title", "tags"]].copy()

In [248]:
print("Final dataset shape:", final_movies_df.shape)
print(final_movies_df.head(5))

Final dataset shape: (4800, 3)
   movie_id                                     title  \
0     19995                                    Avatar
1       285  Pirates of the Caribbean: At World's End
2    206647                                   Spectre
3     49026                     The Dark Knight Rises
4     49529                               John Carter

                                                                                                                      tags
0  in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn bet...
1  captain barbossa, long believed to be dead, has come back to life and is headed to the edge of the earth with will t...
2  a cryptic message from bond’s past sends him on a trail to uncover a sinister organization. while m battles politica...
3  following the death of district attorney harvey dent, batman assumes responsibility for dent's crimes to protect the...
4  john carter is a war-weary, former military captain who's inexplicably transported to the mysterious and exotic plan...

## Save Processed Dataset
Persist the final preprocessing result for vectorization and modeling.

### 13) Save final output

In [249]:
output_path = "../data/processed_movies.csv"
final_movies_df.to_csv(output_path, index=False)

In [250]:
print(f"Processed dataset saved to: {output_path}")
print("Saved file preview:")
print(pd.read_csv(output_path).head(3))

Processed dataset saved to: ../data/processed_movies.csv
Saved file preview:
   movie_id                                     title  \
0     19995                                    Avatar
1       285  Pirates of the Caribbean: At World's End
2    206647                                   Spectre

                                                                                                                      tags
0  in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn bet...
1  captain barbossa, long believed to be dead, has come back to life and is headed to the edge of the earth with will t...
2  a cryptic message from bond’s past sends him on a trail to uncover a sinister organization. while m battles politica...

### 14) Final sanity checks

In [251]:
print("Unique movie_id count:", final_movies_df["movie_id"].nunique())
print("Total rows:", len(final_movies_df))
print("Any missing tags:", final_movies_df["tags"].isnull().any())
print("Empty-tag rows:", (final_movies_df["tags"].str.len() == 0).sum())

Unique movie_id count: 4800
Total rows: 4800
Any missing tags: False
Empty-tag rows: 0